server.port=8099
messaging-client.base-service-url=http://localhost:8080
messaging-client.authorization.username=user
messaging-client.authorization.password=password
messaging-client.connection.connection-timeout=5000
messaging-client.connection.socket-timeout=30000
messaging-client.armaghan-negar.originator=
messaging-client.kave-negar.originator=2000660110
messaging-client.kave-negar.api-key=75454B7074727A526A54744F2B2F55494D3954757A7351682F43765042316867656335435A455155414A493D
messaging-client.ssl.checkValidity=false
messaging-client.provider=KAVE_NEGAR
management.tracing.enabled=false
chapar.messaging-client.base-service-url=http://localhost:8080
chapar.messaging-client.client-id=valid_client
chapar.messaging-client.client-secret=valid_secret
###### Cache Config ######
####{ Redis Common Config
# ?? ???? ???? ???? ??? ????? ?? ?? ???? ??????? ?? ???
tedisson.redis.enabled=false
tedisson.local.cache-provider=caffeine
