/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.10.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.tosan.client.messaging.starter.provider.armaghan.facade;

import com.tosan.client.messaging.starter.provider.armaghan.exception.ArmaghanNegarRuntimeException;
import com.tosan.client.messaging.starter.provider.armaghan.model.*;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.10.0")
@Validated
@Tag(name = "Get States", description = "the Get States API")
public interface WebserviceApi {

    /**
     * POST /webservice/rest/getMessageState : MessageState
     * &lt;p&gt;&lt;b&gt;NOTE: &lt;/b&gt;&lt;span&gt;if the referenceId is &lt;b&gt;NULL&lt;/b&gt;, you will get &lt;b&gt;NULL&lt;/b&gt;.&lt;/span&gt;&lt;/p&gt; &lt;p&gt;&lt;b&gt;NOTE: &lt;/b&gt;&lt;span&gt;if the referenceId is &lt;b&gt;not found&lt;/b&gt;, you will get &lt;b&gt;-100&lt;/b&gt; in state.&lt;/span&gt;&lt;/p&gt; &lt;h4&gt;Message States:&lt;/h4&gt; &lt;ul&gt;     &lt;li&gt;&lt;b&gt;&lt;i&gt;0&lt;/i&gt;&lt;/b&gt; &#x3D;&gt; &lt;b&gt;&lt;i&gt;scheduled&lt;/i&gt;&lt;/b&gt;&lt;/li&gt;     &lt;li&gt;&lt;b&gt;&lt;i&gt;1&lt;/i&gt;&lt;/b&gt; &#x3D;&gt; &lt;b&gt;&lt;i&gt;sent&lt;/i&gt;&lt;/b&gt;&lt;/li&gt;     &lt;li&gt;&lt;b&gt;&lt;i&gt;2&lt;/i&gt;&lt;/b&gt; &#x3D;&gt; &lt;b&gt;&lt;i&gt;delivered&lt;/i&gt;&lt;/b&gt;&lt;/li&gt;     &lt;li&gt;&lt;b&gt;&lt;i&gt;3&lt;/i&gt;&lt;/b&gt; &#x3D;&gt; &lt;b&gt;&lt;i&gt;not delivered&lt;/i&gt;&lt;/b&gt;&lt;/li&gt;     &lt;li&gt;&lt;b&gt;&lt;i&gt;4&lt;/i&gt;&lt;/b&gt; &#x3D;&gt; &lt;b&gt;&lt;i&gt;unknown&lt;/i&gt;&lt;/b&gt;&lt;/li&gt;     &lt;li&gt;&lt;b&gt;&lt;i&gt;5&lt;/i&gt;&lt;/b&gt; &#x3D;&gt; &lt;b&gt;&lt;i&gt;ready&lt;/i&gt;&lt;/b&gt;&lt;/li&gt;     &lt;li&gt;&lt;b&gt;&lt;i&gt;6&lt;/i&gt;&lt;/b&gt; &#x3D;&gt; &lt;b&gt;&lt;i&gt;canceled&lt;/i&gt;&lt;/b&gt;&lt;/li&gt; &lt;/ul&gt;
     *
     * @param messagestateRequest  (optional)
     * @return Success (status code 200)
     */
    @Operation(
            operationId = "messagestate",
            summary = "MessageState",
            description = "<p><b>NOTE: </b><span>if the referenceId is <b>NULL</b>, you will get <b>NULL</b>.</span></p> <p><b>NOTE: </b><span>if the referenceId is <b>not found</b>, you will get <b>-100</b> in state.</span></p> <h4>Message States:</h4> <ul>     <li><b><i>0</i></b> => <b><i>scheduled</i></b></li>     <li><b><i>1</i></b> => <b><i>sent</i></b></li>     <li><b><i>2</i></b> => <b><i>delivered</i></b></li>     <li><b><i>3</i></b> => <b><i>not delivered</i></b></li>     <li><b><i>4</i></b> => <b><i>unknown</i></b></li>     <li><b><i>5</i></b> => <b><i>ready</i></b></li>     <li><b><i>6</i></b> => <b><i>canceled</i></b></li> </ul>",
            tags = { "Get States" },
            responses = {
                    @ApiResponse(responseCode = "200", description = "Success", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = Messagestate200Response.class))
                    })
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/webservice/rest/getMessageState",
            produces = { "application/json" },
            consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)

    Messagestate200Response messagestate(
            @Parameter(name = "MessagestateRequest", description = "") @Valid @RequestBody(required = false) MessagestateRequest messagestateRequest
    ) throws
            ArmaghanNegarRuntimeException;


    /**
     * POST /webservice/rest/getReceivedMessages : ReceiveIncomingMessages
     * &lt;ul&gt;     &lt;li&gt;The only required input variables are &lt;b&gt;&lt;i&gt;username&lt;/i&gt;&lt;/b&gt; and &lt;b&gt;&lt;i&gt;password&lt;/i&gt;&lt;/b&gt;.&lt;/li&gt;     &lt;li&gt;Variables &lt;b&gt;&lt;i&gt;from&lt;/i&gt;&lt;/b&gt; and &lt;b&gt;&lt;i&gt;to&lt;/i&gt;&lt;/b&gt; are unix timestamp in milli seconds.&lt;/li&gt;     &lt;li&gt;This list API is paginated. &lt;b&gt;&lt;i&gt;page&lt;/i&gt;&lt;/b&gt; is zero-based and defaulted to 0. &lt;b&gt;&lt;i&gt;size&lt;/i&gt;&lt;/b&gt; is the length of the result and defaulted to 100.&lt;/li&gt;     &lt;li&gt;when setting &lt;b&gt;&lt;i&gt;afterId&lt;/i&gt;&lt;/b&gt; in request, results are after the specified id.&lt;/li&gt;     &lt;li&gt;&lt;b&gt;&lt;i&gt;originator&lt;/i&gt;&lt;/b&gt; is the mobile number the message is sent from.&lt;/li&gt;     &lt;li&gt;&lt;b&gt;&lt;i&gt;destination&lt;/i&gt;&lt;/b&gt; is the number the message is sent to. for example it may start with 50004.&lt;/li&gt;     &lt;li&gt;you can also search messages based on &lt;b&gt;&lt;i&gt;content&lt;/i&gt;&lt;/b&gt;. Be aware that the search is not based on words. For example, if you search \&quot;ab\&quot;, messages containing \&quot;xxabxx\&quot; are also shown.&lt;/li&gt;     &lt;li&gt;if you want to get incoming messages for a specific service, you can add its tag to &lt;b&gt;&lt;i&gt;serviceTag&lt;/i&gt;&lt;/b&gt;.&lt;/li&gt; &lt;/ul&gt;
     *
     * @param receiveincomingmessagesRequest  (optional)
     * @return Success (status code 200)
     */
    @Operation(
            operationId = "receiveincomingmessages",
            summary = "ReceiveIncomingMessages",
            description = "<ul>     <li>The only required input variables are <b><i>username</i></b> and <b><i>password</i></b>.</li>     <li>Variables <b><i>from</i></b> and <b><i>to</i></b> are unix timestamp in milli seconds.</li>     <li>This list API is paginated. <b><i>page</i></b> is zero-based and defaulted to 0. <b><i>size</i></b> is the length of the result and defaulted to 100.</li>     <li>when setting <b><i>afterId</i></b> in request, results are after the specified id.</li>     <li><b><i>originator</i></b> is the mobile number the message is sent from.</li>     <li><b><i>destination</i></b> is the number the message is sent to. for example it may start with 50004.</li>     <li>you can also search messages based on <b><i>content</i></b>. Be aware that the search is not based on words. For example, if you search \"ab\", messages containing \"xxabxx\" are also shown.</li>     <li>if you want to get incoming messages for a specific service, you can add its tag to <b><i>serviceTag</i></b>.</li> </ul>",
            tags = { "Receive Messages" },
            responses = {
                    @ApiResponse(responseCode = "200", description = "Success", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = Receiveincomingmessages200Response.class))
                    })
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/webservice/rest/getReceivedMessages",
            produces = { "application/json" },
            consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)

    Receiveincomingmessages200Response receiveincomingmessages(
            @Parameter(name = "ReceiveincomingmessagesRequest", description = "") @Valid @RequestBody(required = false) ReceiveincomingmessagesRequest receiveincomingmessagesRequest
    ) throws
            ArmaghanNegarRuntimeException;


    /**
     * GET /webservice/rest/getReceivedMessages : ReceiveIncomingMessages
     * ReceiveIncomingMessages
     *
     * @param username  (optional)
     * @param password  (optional)
     * @param page  (optional)
     * @param size  (optional)
     * @param from unix timestamp (optional)
     * @param to unix timestamp (optional)
     * @param afterId  (optional)
     * @param destination  (optional)
     * @param originator  (optional)
     * @param content  (optional)
     * @param serviceTag  (optional)
     * @return  (status code 200)
     */
    @Operation(
            operationId = "receiveincomingmessages1",
            summary = "ReceiveIncomingMessages",
            description = "ReceiveIncomingMessages",
            tags = { "Receive Messages" },
            responses = {
                    @ApiResponse(responseCode = "200", description = "")
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/webservice/rest/getReceivedMessages"
    )
    @ResponseStatus(HttpStatus.OK)

    void receiveincomingmessages1(
            @Parameter(name = "username", description = "", in = ParameterIn.QUERY) @org.springframework.cloud.openfeign.SpringQueryMap @Valid @RequestParam(value = "username", required = false) String username,
            @Parameter(name = "password", description = "", in = ParameterIn.QUERY) @org.springframework.cloud.openfeign.SpringQueryMap @Valid @RequestParam(value = "password", required = false) String password,
            @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @org.springframework.cloud.openfeign.SpringQueryMap @Valid @RequestParam(value = "page", required = false) String page,
            @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @org.springframework.cloud.openfeign.SpringQueryMap @Valid @RequestParam(value = "size", required = false) String size,
            @Parameter(name = "from", description = "unix timestamp", in = ParameterIn.QUERY) @org.springframework.cloud.openfeign.SpringQueryMap @Valid @RequestParam(value = "from", required = false) String from,
            @Parameter(name = "to", description = "unix timestamp", in = ParameterIn.QUERY) @org.springframework.cloud.openfeign.SpringQueryMap @Valid @RequestParam(value = "to", required = false) String to,
            @Parameter(name = "afterId", description = "", in = ParameterIn.QUERY) @org.springframework.cloud.openfeign.SpringQueryMap @Valid @RequestParam(value = "afterId", required = false) String afterId,
            @Parameter(name = "destination", description = "", in = ParameterIn.QUERY) @org.springframework.cloud.openfeign.SpringQueryMap @Valid @RequestParam(value = "destination", required = false) String destination,
            @Parameter(name = "originator", description = "", in = ParameterIn.QUERY) @org.springframework.cloud.openfeign.SpringQueryMap @Valid @RequestParam(value = "originator", required = false) String originator,
            @Parameter(name = "content", description = "", in = ParameterIn.QUERY) @org.springframework.cloud.openfeign.SpringQueryMap @Valid @RequestParam(value = "content", required = false) String content,
            @Parameter(name = "serviceTag", description = "", in = ParameterIn.QUERY) @org.springframework.cloud.openfeign.SpringQueryMap @Valid @RequestParam(value = "serviceTag", required = false) String serviceTag
    ) throws
            ArmaghanNegarRuntimeException;


    /**
     * POST /webservice/rest/sendMessageManyToMany : SendManyToManyMessage
     * SendManyToManyMessage
     *
     * @param sendmanytomanymessageRequest  (optional)
     * @return Success (status code 200)
     */
    @Operation(
            operationId = "sendmanytomanymessage",
            summary = "SendManyToManyMessage",
            description = "SendManyToManyMessage",
            tags = { "Send Messages" },
            responses = {
                    @ApiResponse(responseCode = "200", description = "Success", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = Sendonetomanymessage200Response.class))
                    })
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/webservice/rest/sendMessageManyToMany",
            produces = { "application/json" },
            consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)

    Sendonetomanymessage200Response sendmanytomanymessage(
            @Parameter(name = "SendmanytomanymessageRequest", description = "") @Valid @RequestBody(required = false) SendmanytomanymessageRequest sendmanytomanymessageRequest
    ) throws
            ArmaghanNegarRuntimeException;


    /**
     * POST /webservice/rest/sendMessageOneToMany : SendOneToManyMessage
     * SendOneToManyMessage
     *
     * @param sendonetomanymessageRequest  (optional)
     * @return Success (status code 200)
     */
    @Operation(
            operationId = "sendonetomanymessage",
            summary = "SendOneToManyMessage",
            description = "SendOneToManyMessage",
            tags = { "Send Messages" },
            responses = {
                    @ApiResponse(responseCode = "200", description = "Success", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = Sendonetomanymessage200Response.class))
                    })
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/webservice/rest/sendMessageOneToMany",
            produces = { "application/json" },
            consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)

    Sendonetomanymessage200Response sendonetomanymessage(
            @Parameter(name = "SendonetomanymessageRequest", description = "") @Valid @RequestBody(required = false) SendonetomanymessageRequest sendonetomanymessageRequest
    ) throws
            ArmaghanNegarRuntimeException;


    /**
     * GET /webservice/rest/sendOneToOne : SendOneToOneMessage
     * SendOneToOneMessage
     *
     * @param username  (optional)
     * @param password  (optional)
     * @param from  (optional)
     * @param to  (optional)
     * @param message  (optional)
     * @return Success (status code 200)
     */
    @Operation(
            operationId = "sendonetoonemessage",
            summary = "SendOneToOneMessage",
            description = "SendOneToOneMessage",
            tags = { "Send Messages" },
            responses = {
                    @ApiResponse(responseCode = "200", description = "Success", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = Sendonetomanymessage200Response.class))
                    })
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/webservice/rest/sendOneToOne",
            produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)

    Sendonetomanymessage200Response sendonetoonemessage(
            @Parameter(name = "username", description = "", in = ParameterIn.QUERY) @org.springframework.cloud.openfeign.SpringQueryMap @Valid @RequestParam(value = "username", required = false) String username,
            @Parameter(name = "password", description = "", in = ParameterIn.QUERY) @org.springframework.cloud.openfeign.SpringQueryMap @Valid @RequestParam(value = "password", required = false) String password,
            @Parameter(name = "from", description = "", in = ParameterIn.QUERY) @org.springframework.cloud.openfeign.SpringQueryMap @Valid @RequestParam(value = "from", required = false) String from,
            @Parameter(name = "to", description = "", in = ParameterIn.QUERY) @org.springframework.cloud.openfeign.SpringQueryMap @Valid @RequestParam(value = "to", required = false) String to,
            @Parameter(name = "message", description = "", in = ParameterIn.QUERY) @org.springframework.cloud.openfeign.SpringQueryMap @Valid @RequestParam(value = "message", required = false) String message
    ) throws
            ArmaghanNegarRuntimeException;


    /**
     * POST /webservice/rest/sendParameterizedMessage : SendParameterizedMessage
     * SendParameterizedMessage
     *
     * @param sendparameterizedmessageRequest  (optional)
     * @return  (status code 200)
     */
    @Operation(
            operationId = "sendparameterizedmessage",
            summary = "SendParameterizedMessage",
            description = "SendParameterizedMessage",
            tags = { "Send Messages" },
            responses = {
                    @ApiResponse(responseCode = "200", description = "")
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/webservice/rest/sendParameterizedMessage",
            consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)

    void sendparameterizedmessage(
            @Parameter(name = "SendparameterizedmessageRequest", description = "") @Valid @RequestBody(required = false) SendparameterizedmessageRequest sendparameterizedmessageRequest
    ) throws
            ArmaghanNegarRuntimeException;


    /**
     * GET /webservice/rest/v2/sendParameterizedMessage : SendParameterizedMessage
     * SendParameterizedMessage
     *
     * @param username  (optional)
     * @param password  (optional)
     * @param template  (optional)
     * @param destinations seperated with comma (optional)
     * @param parameters seperated with caret (^) (optional)
     * @return  (status code 200)
     */
    @Operation(
            operationId = "sendparameterizedmessage1",
            summary = "SendParameterizedMessage",
            description = "SendParameterizedMessage",
            tags = { "Send Messages" },
            responses = {
                    @ApiResponse(responseCode = "200", description = "")
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/webservice/rest/v2/sendParameterizedMessage"
    )
    @ResponseStatus(HttpStatus.OK)

    void sendparameterizedmessage1(
            @Parameter(name = "username", description = "", in = ParameterIn.QUERY) @org.springframework.cloud.openfeign.SpringQueryMap @Valid @RequestParam(value = "username", required = false) String username,
            @Parameter(name = "password", description = "", in = ParameterIn.QUERY) @org.springframework.cloud.openfeign.SpringQueryMap @Valid @RequestParam(value = "password", required = false) String password,
            @Parameter(name = "template", description = "", in = ParameterIn.QUERY) @org.springframework.cloud.openfeign.SpringQueryMap @Valid @RequestParam(value = "template", required = false) String template,
            @Parameter(name = "destinations", description = "seperated with comma", in = ParameterIn.QUERY) @org.springframework.cloud.openfeign.SpringQueryMap @Valid @RequestParam(value = "destinations", required = false) String destinations,
            @Parameter(name = "parameters", description = "seperated with caret (^)", in = ParameterIn.QUERY) @org.springframework.cloud.openfeign.SpringQueryMap @Valid @RequestParam(value = "parameters", required = false) String parameters
    ) throws
            ArmaghanNegarRuntimeException;


    /**
     * POST /webservice/rest/getUserInfo : UserInfo
     * UserInfo
     *
     * @param userinfoRequest  (optional)
     * @return  (status code 200)
     */
    @Operation(
            operationId = "userinfo",
            summary = "UserInfo",
            description = "UserInfo",
            tags = { "Get States" },
            responses = {
                    @ApiResponse(responseCode = "200", description = "")
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/webservice/rest/getUserInfo",
            consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)

    void userinfo(
            @Parameter(name = "UserinfoRequest", description = "") @Valid @RequestBody(required = false) UserinfoRequest userinfoRequest
    ) throws
            ArmaghanNegarRuntimeException;


    /**
     * GET /webservice/rest/getUserInfo : UserInfo
     * UserInfo
     *
     * @param username  (optional)
     * @param password  (optional)
     * @return  (status code 200)
     */
    @Operation(
            operationId = "userinfo1",
            summary = "UserInfo",
            description = "UserInfo",
            tags = { "Get States" },
            responses = {
                    @ApiResponse(responseCode = "200", description = "")
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/webservice/rest/getUserInfo"
    )
    @ResponseStatus(HttpStatus.OK)

    void userinfo1(
            @Parameter(name = "username", description = "", in = ParameterIn.QUERY) @org.springframework.cloud.openfeign.SpringQueryMap @Valid @RequestParam(value = "username", required = false) String username,
            @Parameter(name = "password", description = "", in = ParameterIn.QUERY) @org.springframework.cloud.openfeign.SpringQueryMap @Valid @RequestParam(value = "password", required = false) String password
    ) throws
            ArmaghanNegarRuntimeException;

}
